image: ${RUNNER_TOOLS_IMAGE_URI}:serverless-1.34.1

stages:
  - test
  - publish

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - yarn
    - yarn test

publish:
  stage: publish
  script:
    - sed -i '/"private":[[:space:]]true/d' package.json
    - yarn
    - yarn publish --registry https://registry.bespokify.com/ --non-interactive
  only:
    - tags
    - /^v\d+\.\d+\.\d+$/
